# Generated by Django 4.0.6 on 2022-08-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активная доска'),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_boards', to='projects.project', verbose_name='Проект'),
        ),
    ]
